// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI1sdKCnmG0rUT6_MWcycSoUC1gR8fVeQ',
    appId: '1:226275661829:web:469f1b7e7b5181cec6a46c',
    messagingSenderId: '226275661829',
    projectId: 'travelapp-f4166',
    authDomain: 'travelapp-f4166.firebaseapp.com',
    storageBucket: 'travelapp-f4166.appspot.com',
    measurementId: 'G-3QLXD48D2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ATgWe490NtJ-9C3dPnOtYF98a2dR43M',
    appId: '1:226275661829:android:96a77b57d10da3eec6a46c',
    messagingSenderId: '226275661829',
    projectId: 'travelapp-f4166',
    storageBucket: 'travelapp-f4166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcVoIwa7zXuNbqRnh5EbOXO26WRyvQQHA',
    appId: '1:226275661829:ios:0f5f85e229e7873dc6a46c',
    messagingSenderId: '226275661829',
    projectId: 'travelapp-f4166',
    storageBucket: 'travelapp-f4166.appspot.com',
    iosClientId: '226275661829-n1abn75m2v15p6g75tv7a7knp0f5o4fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcVoIwa7zXuNbqRnh5EbOXO26WRyvQQHA',
    appId: '1:226275661829:ios:0f5f85e229e7873dc6a46c',
    messagingSenderId: '226275661829',
    projectId: 'travelapp-f4166',
    storageBucket: 'travelapp-f4166.appspot.com',
    iosClientId: '226275661829-n1abn75m2v15p6g75tv7a7knp0f5o4fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
